# Pandas with ONE Dataset: `students.csv`
## Beginner → Intermediate, cell by cell

**Teaching approach:** We use one student dataset from beginning to end. There is **no Series section**. We start directly with reading a CSV and then progressively learn Pandas operations on the same `df`.

The Kaggle page you referenced is a `student-data.csv` dataset with 31 columns and a single CSV file. citeturn0search0

For this teaching notebook, `students.csv` is supplied beside this notebook so every exercise is runnable. The dataset contains student identity, demographic, attendance, study hours, subject marks, assignments, absences, average score, grade, and pass/fail information.

### Levels
- 🟢 Beginner: reading, inspecting, selecting, filtering, cleaning
- 🟡 Intermediate: grouping, aggregation, sorting, strings, merging, reshaping, dates
- 🔵 Challenge: practical analysis and interview questions

**Important:** Every major command is in a separate code cell so you can teach and demonstrate it line by line.

In [1]:
print(8)

8

## 1. Import Pandas

In [2]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

## 2. Read the CSV — our first Pandas operation
This is the first real operation. `read_csv()` loads a CSV file into a DataFrame.

In [3]:
df = pd.read_csv('../datset/students.csv')

In [4]:
df

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

## 3. Understand what we loaded

In [6]:
type(df)

pandas.DataFrame

shape function that load the total number of rows and columns

In [ ]:
df.shape  # it will  return 20,16 -20-rows ,16-columns

(20, 16)

In [8]:
df.columns

Index(['student_id', 'name', 'gender', 'age', 'city', 'department',
       'attendance', 'study_hours', 'math', 'science', 'english',
       'assignments', 'absences', 'average_score', 'grade', 'passed'],
      dtype='str')

In [9]:
df.dtypes

student_id         int64
name                 str
gender               str
age                int64
city                 str
department           str
attendance         int64
study_hours        int64
math               int64
science            int64
english            int64
assignments        int64
absences           int64
average_score    float64
grade                str
passed              bool
dtype: object

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     20 non-null     int64
 1   name           20 non-null     str
 2   gender         20 non-null     str
 3   age            20 non-null     int64
 4   city           20 non-null     str
 5   department     20 non-null     str
 6   attendance     20 non-null     int64
 7   study_hours    20 non-null     int64
 8   math           20 non-null     int64
 9   science        20 non-null     int64
 10  english        20 non-null     int64
 11  assignments    20 non-null     int64
 12  absences       20 non-null     int64
 13  average_score  20 non-null     float64
 14  grade          20 non-null     str
 15  passed         20 non-null     bool
dtypes: bool(1), float64(1), int64(9), str(5)
memory usage: 2.9 KB

### Student question
**What is `df`?**

It is a Pandas **DataFrame** containing rows and columns from `students.csv`.

**What does `df.shape` return?**

It returns `(number_of_rows, number_of_columns)`.

## 4. View the first rows

In [11]:
df.head(2)

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.5,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.0,C,True

In [12]:
df.head(3)

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.5,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.0,C,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.5,A,True

In [13]:
df.head(10)

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True

## 5. View the last rows

In [14]:
df.tail()

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

In [15]:
df.tail(3)

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

## 6. Inspect random students

In [16]:
df.sample(5, random_state=42) #randomstate = 42 -set a seed to gernate a pseudo number generator in ML to ensure that result are fully reproducible.

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True

## 7. Select ONE column
A column can be selected using square brackets.

**Syntax:** `df['column_name']`

In [17]:
df['name']

0       Alice
1         Bob
2     Charlie
3       Diana
4        Evan
5       Fiona
6      George
7      Hannah
8         Ian
9       Julia
10      Kevin
11       Lily
12    Michael
13       Nina
14      Oscar
15      Priya
16      Quinn
17     Rachel
18        Sam
19       Tina
Name: name, dtype: str

In [18]:
df['age']

0     20
1     21
2     19
3     22
4     20
5     21
6     23
7     20
8     22
9     19
10    21
11    20
12    24
13    22
14    21
15    20
16    23
17    19
18    22
19    21
Name: age, dtype: int64

In [19]:
df['math']

0     88
1     72
2     91
3     94
4     75
5     86
6     65
7     89
8     70
9     96
10    84
11    68
12    61
13    92
14    77
15    90
16    87
17    64
18    73
19    95
Name: math, dtype: int64

## 8. Select MULTIPLE columns

In [20]:
df[['name', 'age']]

       name  age
0     Alice   20
1       Bob   21
2   Charlie   19
3     Diana   22
4      Evan   20
5     Fiona   21
6    George   23
7    Hannah   20
8       Ian   22
9     Julia   19
10    Kevin   21
11     Lily   20
12  Michael   24
13     Nina   22
14    Oscar   21
15    Priya   20
16    Quinn   23
17   Rachel   19
18      Sam   22
19     Tina   21

In [21]:
df[['name', 'math', 'science', 'english']]

       name  math  science  english
0     Alice    88       85       90
1       Bob    72       70       76
2   Charlie    91       93       88
3     Diana    94       90       92
4      Evan    75       78       81
5     Fiona    86       88       84
6    George    65       62       69
7    Hannah    89       91       87
8       Ian    70       74       79
9     Julia    96       94       95
10    Kevin    84       82       86
11     Lily    68       71       73
12  Michael    61       59       65
13     Nina    92       89       94
14    Oscar    77       80       82
15    Priya    90       92       89
16    Quinn    87       85       91
17   Rachel    64       66       70
18      Sam    73       76       78
19     Tina    95       91       93

In [22]:
df[['name', 'department', 'average_score', 'grade']]

       name  department  average_score grade
0     Alice          IT          87.50     B
1       Bob  Management          73.00     C
2   Charlie          IT          90.50     A
3     Diana     Science          92.75     A
4      Evan  Management          78.25     C
5     Fiona          IT          85.75     B
6    George     Science          65.75     D
7    Hannah          IT          89.75     A
8       Ian  Management          73.75     C
9     Julia     Science          95.50     A
10    Kevin          IT          83.75     B
11     Lily  Management          70.50     C
12  Michael     Science          61.25     D
13     Nina          IT          91.50     A
14    Oscar  Management          79.25     B
15    Priya     Science          91.00     A
16    Quinn          IT          87.75     B
17   Rachel     Science          66.25     D
18      Sam  Management          75.50     C
19     Tina          IT          93.25     A

 ## loc is used to select rows and columns by their labels or by a condition.
 Syntax:
 df.loc[row, column]
 For instance:

 df.loc[0:3, ['name', 'math']]

 location using labels/conditions.

## 9. Selecting rows with `loc`
`loc` selects using labels or conditions.

In [23]:
df.loc[0]

student_id            1001
name                 Alice
gender                   F
age                     20
city             Kathmandu
department              IT
attendance              92
study_hours             12
math                    88
science                 85
english                 90
assignments             87
absences                 2
average_score         87.5
grade                    B
passed                True
Name: 0, dtype: object

In [24]:
df.loc[1:4]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True

In [ ]:
df.loc[0:4, ['name', 'math', 'science']] #here it will select 3 columns with 0 index to index 4values.

      name  math  science
0    Alice    88       85
1      Bob    72       70
2  Charlie    91       93
3    Diana    94       90
4     Evan    75       78

In [26]:
df.loc[df['math'] > 80, ['name', 'math']]

       name  math
0     Alice    88
2   Charlie    91
3     Diana    94
5     Fiona    86
7    Hannah    89
9     Julia    96
10    Kevin    84
13     Nina    92
15    Priya    90
16    Quinn    87
19     Tina    95

iloc is used to select rows and columns by their integer position (index number).
Syntax:
df.iloc[row, column]
For instance:
df.iloc[0:4, 0:3]
This selects:

Rows 0 to 3
Columns 0 to 2

Differences:
loc → labels / conditions
iloc → integer positions

| Point                   | `loc`                           | `iloc`                              |
| ----------------------- | ------------------------------- | ----------------------------------- |
| **1. Selection method** | Selects using **labels/names**  | Selects using **integer positions** |
| **2. Syntax**           | `df.loc[row, column]`           | `df.iloc[row, column]`              |
| **3. Example**          | `df.loc[0:3, ['name', 'math']]` | `df.iloc[0:4, 0:2]`                 |

## 10. Selecting rows with `iloc`
`iloc` selects using integer positions.

In [27]:
df.iloc[0]

student_id            1001
name                 Alice
gender                   F
age                     20
city             Kathmandu
department              IT
attendance              92
study_hours             12
math                    88
science                 85
english                 90
assignments             87
absences                 2
average_score         87.5
grade                    B
passed                True
Name: 0, dtype: object

In [28]:
df.iloc[0:5]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True

In [29]:
df.iloc[(df['math'] > 80).values,0]

0     1001
2     1003
3     1004
5     1006
7     1008
9     1010
10    1011
13    1014
15    1016
16    1017
19    1020
Name: student_id, dtype: int64

df.iloc[0:5, 0:4]
       ↑       ↑
     rows   columns

In [30]:
df.iloc[0:5, 0:4]

   student_id     name gender  age
0        1001    Alice      F   20
1        1002      Bob      M   21
2        1003  Charlie      M   19
3        1004    Diana      F   22
4        1005     Evan      M   20

In [31]:
df.iloc[0:5, [1, 8, 9]]

      name  math  science
0    Alice    88       85
1      Bob    72       70
2  Charlie    91       93
3    Diana    94       90
4     Evan    75       78

In [32]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
df =pd.read_excel('',encoding='utf-8')

TypeError: read_excel() got an unexpected keyword argument 'encoding'

### `loc` vs `iloc`
- `loc` → label/condition based
- `iloc` → integer-position based

**Interview question:** When would you use `iloc`?  
When you want to select by row/column position rather than column names.

## 11. Basic filtering — one condition

In [ ]:
df[df['age'] > 21] #it will return the rows whose value of age are greater than 21.

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True

In [ ]:
df[df['math'] >= 80]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

In [ ]:
df[df['attendance'] < 80]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True

In [ ]:
df[df['city'] == 'Kathmandu']

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

In [ ]:
df[df['department'] == 'IT']

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

## 12. Filtering — multiple conditions

In [ ]:
df[(df['math'] > 80) & (df['science'] > 80)]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

This code filters students based on two conditions.
`df['attendance'] >= 85` checks if attendance is at least 85%.
`df['average_score'] >= 80` checks if the average score is at least 80.
`&` means **AND**, so both conditions must be true.
Therefore, it returns students with **attendance ≥ 85 and average score ≥ 80**.

In [ ]:
df[(df['attendance'] >= 85) & (df['average_score'] >= 80)]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

In [ ]:
df[(df['city'] == 'Kathmandu') | (df['city'] == 'Pokhara')]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

## 13. `isin()`
isin() is used to check whether values in a column belong to a specific list of values.
Syntax:
df[df['column_name'].isin([value1, value2, value3])]


For example, if you want to find students from Kathmandu or Pokhara:
df[df['city'].isin(['Kathmandu', 'Pokhara'])]

df['city'] → selects the city column.
.isin(['Kathmandu', 'Pokhara']) → checks whether each city is Kathmandu or Pokhara.
df[...] → returns only the students who match.

“Give me rows where the value is one of these specified values.”

In [ ]:
df[df['city'].isin(['Kathmandu', 'Pokhara'])]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

In [ ]:
df[df['department'].isin(['IT', 'Science'])]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

## 14. `between()`

between() is used to filter rows where a column's value falls within a specific range.
df[df['column_name'].between(lower_value, upper_value)]

For example:
df[df['age'].between(18, 22)] -This selects students whose age is 18, 19, 20, 21, or 22.

This is why because of this:
df[(df['age'] >= 18) & (df['age'] <= 22)]

between() = filter values within a range.

In [ ]:
df[df['age'].between(20, 22)]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

In [ ]:
df[df['average_score'].between(70, 90)]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True

## 15. Add a new column

syntax:
df['new_column'] = value

For instance:
df['total_score'] = df['math'] + df['science'] + df['english']
Here, Pandas calculates the total score for each student and stores it in the new total_score column.

In [ ]:
df['total_marks'] = df['math'] + df['science'] + df['english'] + df['assignments']
df

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed,total_marks
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True,350
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True,292
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True,362
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True,371
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True,313
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True,343
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True,263
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True,359
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True,295
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True,382
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True,335
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True,282
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True,245
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True,366
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True,317
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True,364
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True,351
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True,265
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True,302
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True,373

In [ ]:
df[['name', 'total_marks']]

       name  total_marks
0     Alice          350
1       Bob          292
2   Charlie          362
3     Diana          371
4      Evan          313
5     Fiona          343
6    George          263
7    Hannah          359
8       Ian          295
9     Julia          382
10    Kevin          335
11     Lily          282
12  Michael          245
13     Nina          366
14    Oscar          317
15    Priya          364
16    Quinn          351
17   Rachel          265
18      Sam          302
19     Tina          373

## 16. Add a column using calculation

In [ ]:
df['average_from_subjects'] = df['total_marks'] / 4

In [ ]:
df[['name', 'average_from_subjects']]

       name  average_from_subjects
0     Alice                  87.50
1       Bob                  73.00
2   Charlie                  90.50
3     Diana                  92.75
4      Evan                  78.25
5     Fiona                  85.75
6    George                  65.75
7    Hannah                  89.75
8       Ian                  73.75
9     Julia                  95.50
10    Kevin                  83.75
11     Lily                  70.50
12  Michael                  61.25
13     Nina                  91.50
14    Oscar                  79.25
15    Priya                  91.00
16    Quinn                  87.75
17   Rachel                  66.25
18      Sam                  75.50
19     Tina                  93.25

## 17. Add a column using a condition

In [ ]:
df['pass_status'] = df['average_score'] >= 60

In [ ]:
df[['name', 'average_score', 'pass_status']]

       name  average_score  pass_status
0     Alice          87.50         True
1       Bob          73.00         True
2   Charlie          90.50         True
3     Diana          92.75         True
4      Evan          78.25         True
5     Fiona          85.75         True
6    George          65.75         True
7    Hannah          89.75         True
8       Ian          73.75         True
9     Julia          95.50         True
10    Kevin          83.75         True
11     Lily          70.50         True
12  Michael          61.25         True
13     Nina          91.50         True
14    Oscar          79.25         True
15    Priya          91.00         True
16    Quinn          87.75         True
17   Rachel          66.25         True
18      Sam          75.50         True
19     Tina          93.25         True

## 18. `np.where()` for categories
np.where() is used to create a new column based on a condition. It allows us to assign one value when the condition is True and another value when it is False.
np.where(condition, value_if_true, value_if_false)

df['performance'] = np.where(df['average_score'] >= 80, 'Excellent', 'Needs Improvement')
This checks the average_score of each student:

If score ≥ 80 → "Excellent"
If score < 80 → "Needs Improvement"

np.where() = if condition is true, give one value; otherwise, give another value.

| Feature            | `df['pass_status'] = df['average_score'] >= 60` | `np.where()`                                    |
| ------------------ | ----------------------------------------------- | ----------------------------------------------- |
| **Result**         | Creates `True` or `False`                       | Creates custom values like `"Pass"` or `"Fail"` |
| **Example output** | `True`, `False`, `True`                         | `"Pass"`, `"Fail"`, `"Pass"`                    |
| **Use**            | When you only need a **Boolean condition**      | When you want **specific categories/labels**    |

In [ ]:
import numpy as np

In [ ]:
df['performance'] = np.where(df['average_score'] >= 80, 'Good', 'Needs Improvement')

In [ ]:
df[['name', 'average_score', 'performance']]

       name  average_score        performance
0     Alice          87.50               Good
1       Bob          73.00  Needs Improvement
2   Charlie          90.50               Good
3     Diana          92.75               Good
4      Evan          78.25  Needs Improvement
5     Fiona          85.75               Good
6    George          65.75  Needs Improvement
7    Hannah          89.75               Good
8       Ian          73.75  Needs Improvement
9     Julia          95.50               Good
10    Kevin          83.75               Good
11     Lily          70.50  Needs Improvement
12  Michael          61.25  Needs Improvement
13     Nina          91.50               Good
14    Oscar          79.25  Needs Improvement
15    Priya          91.00               Good
16    Quinn          87.75               Good
17   Rachel          66.25  Needs Improvement
18      Sam          75.50  Needs Improvement
19     Tina          93.25               Good

## 19. Rename columns:
df.rename(columns={'old_name': 'new_name'}, inplace=True)

Eg:
df.rename(columns={'average_score': 'avg_score'}, inplace=True)
means make the change directly to the original DataFrame.

In [ ]:
df.rename(columns={'study_hours': 'study_hours_per_week'})

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed,total_marks,average_from_subjects
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True,350,87.50
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True,292,73.00
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True,362,90.50
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True,371,92.75
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True,313,78.25
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True,343,85.75
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True,263,65.75
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True,359,89.75
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True,295,73.75
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True,382,95.50
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True,335,83.75
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True,282,70.50
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True,245,61.25
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True,366,91.50
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True,317,79.25
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True,364,91.00
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True,351,87.75
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True,265,66.25
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True,302,75.50
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True,373,93.25

The above returns a new DataFrame view/result. To permanently assign it:

In [ ]:
df = df.rename(columns={'study_hours': 'study_hours_per_week'})

In [ ]:
df.columns

Index(['student_id', 'name', 'gender', 'age', 'city', 'department',
       'attendance', 'study_hours_per_week', 'math', 'science', 'english',
       'assignments', 'absences', 'average_score', 'grade', 'passed',
       'total_marks', 'average_from_subjects', 'pass_status', 'performance'],
      dtype='str')

## 20. Drop a column:
drop() is used to remove a column or row from a DataFrame.

df.drop('column_name', axis=1, inplace=True)
Example:
df.drop('age', axis=1, inplace=True)

Important
axis=1 → means column
axis=0 → means row
inplace=True → changes the original DataFrame

In [ ]:
df = df.drop(columns=['average_from_subjects'])

Index(['student_id', 'name', 'gender', 'age', 'city', 'department',
       'attendance', 'study_hours', 'math', 'science', 'english',
       'assignments', 'absences', 'average_score', 'grade', 'passed',
       'total_marks'],
      dtype='str')

In [ ]:
df.columns

Index(['student_id', 'name', 'gender', 'age', 'city', 'department',
       'attendance', 'study_hours', 'math', 'science', 'english',
       'assignments', 'absences', 'average_score', 'grade', 'passed',
       'total_marks'],
      dtype='str')

## 21. Drop multiple columns
syntax:
df.drop(['column1', 'column2', 'column3'], axis=1, inplace=True)

Remember: [] → multiple columns, axis=1 → columns, inplace=True → change the original DataFrame.

In [ ]:
df = df.drop(columns=['total_marks', 'pass_status', 'performance'])

In [ ]:
df.columns

Index(['student_id', 'name', 'gender', 'age', 'city', 'department',
       'attendance', 'study_hours_per_week', 'math', 'science', 'english',
       'assignments', 'absences', 'average_score', 'grade', 'passed'],
      dtype='str')

## 22. Sort values

sort_values() is used to sort the rows of a DataFrame based on the values in a particular column.
syntax:
df.sort_values('column_name')
By default, it sorts in ascending order (smallest → largest).
examples:
df.sort_values('average_score')-This arranges students from the lowest average score to the

df.sort_values('average_score', ascending=False)


For multiple columns,
df.sort_values(['department', 'average_score'])

This first sorts by department, and then sorts the students within each department by average score.

Remember: sort_values() → sort rows based on column values.

In [ ]:
df.sort_values('math')

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed,total_marks
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True,245
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True,265
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True,263
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True,282
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True,295
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True,292
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True,302
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True,313
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True,317
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True,335
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True,343
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True,351
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True,350
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True,359
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True,364
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True,362
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True,366
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True,371
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True,373
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True,382

In [ ]:
df.sort_values('math', ascending=False)

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True

In [ ]:
df.sort_values(['department', 'average_score'], ascending=[True, False])

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True

## 23. Sort by index:
Not exactly. sort_index() is for sorting the DataFrame by its index, which is usually the row labels, not for sorting the values inside a row.
df.sort_index()

| Function                  | Sorts by                    |
| ------------------------- | --------------------------- |
| `sort_values()`           | Values in a **column**      |
| `sort_index()`            | **Row/column index labels** |
| `df.loc[0].sort_values()` | Values **inside row 0**     |

In [ ]:
df.sort_index()

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

## 24. Unique values

In [35]:
df['city'].unique()

<ArrowStringArray>
['Kathmandu', 'Pokhara', 'Lalitpur', 'Bhaktapur']
Length: 4, dtype: str

In [37]:
df['city'].nunique()

4

In [ ]:
df['department'].unique()

<ArrowStringArray>
['IT', 'Management', 'Science']
Length: 3, dtype: str

In [ ]:
df['grade'].unique()

<ArrowStringArray>
['B', 'C', 'A', 'D']
Length: 4, dtype: str

## 25. Number of unique values

In [ ]:
df['city'].nunique()

4

In [ ]:
df['department'].nunique()

3

## 26. Count categories

In [39]:
df['city'].value_counts()

city
Kathmandu    8
Pokhara      5
Lalitpur     4
Bhaktapur    3
Name: count, dtype: int64

In [ ]:
df['department'].value_counts()

department
IT            8
Management    6
Science       6
Name: count, dtype: int64

In [ ]:
df['grade'].value_counts()

grade
A    7
B    5
C    5
D    3
Name: count, dtype: int64

In [ ]:
df['gender'].value_counts()

gender
F    10
M    10
Name: count, dtype: int64

## 27. Percentages with `normalize=True`

In [40]:
df['department'].value_counts()

department
IT            8
Management    6
Science       6
Name: count, dtype: int64

In [ ]:
df['department'].value_counts(normalize=True)

department
IT            0.4
Management    0.3
Science       0.3
Name: proportion, dtype: float64

In [ ]:
df['grade'].value_counts(normalize=True) * 100

grade
A    35.0
B    25.0
C    25.0
D    15.0
Name: proportion, dtype: float64

## 28. Numeric summary

In [ ]:
df.describe()

,student_id,age,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000,20.00000
mean,1010.50000,21.000000,84.650000,10.050000,80.850000,80.800000,83.100000,81.75000,5.500000,81.62500
std,5.91608,1.414214,8.183906,2.946452,11.485804,10.846295,8.973059,11.13021,3.831998,10.49671
min,1001.00000,19.000000,69.000000,5.000000,61.000000,59.000000,65.000000,60.00000,1.000000,61.25000
25%,1005.75000,20.000000,78.750000,8.000000,71.500000,73.250000,77.500000,73.50000,2.000000,73.56250
50%,1010.50000,21.000000,86.000000,10.000000,85.000000,83.500000,85.000000,84.00000,4.500000,84.75000
75%,1015.25000,22.000000,91.250000,12.250000,90.250000,90.250000,90.250000,91.25000,8.000000,90.62500
max,1020.00000,24.000000,96.000000,15.000000,96.000000,94.000000,95.000000,97.00000,14.000000,95.50000

In [ ]:
df[['math', 'science', 'english', 'average_score']].describe()

            math    science    english  average_score
count  20.000000  20.000000  20.000000       20.00000
mean   80.850000  80.800000  83.100000       81.62500
std    11.485804  10.846295   8.973059       10.49671
min    61.000000  59.000000  65.000000       61.25000
25%    71.500000  73.250000  77.500000       73.56250
50%    85.000000  83.500000  85.000000       84.75000
75%    90.250000  90.250000  90.250000       90.62500
max    96.000000  94.000000  95.000000       95.50000

## 29. Individual statistics

In [ ]:
df['math'].mean()

np.float64(80.85)

In [ ]:
df['math'].median()

np.float64(85.0)

In [ ]:
df['math'].min()

np.int64(61)

In [ ]:
df['math'].max()

np.int64(96)

In [ ]:
df['math'].sum()

np.int64(1617)

In [ ]:
df['math'].std()

np.float64(11.4858035944607)

In [ ]:
df['math'].var()

np.float64(131.92368421052632)

## 30. Find the highest and lowest students

In [ ]:
df.nlargest(5, 'average_score')

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True

In [ ]:
df.nsmallest(5, 'average_score')

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True

## 31. Missing values — first check

In [ ]:
df.isna()

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isna().sum()

student_id              0
name                    0
gender                  0
age                     0
city                    0
department              0
attendance              0
study_hours_per_week    0
math                    0
science                 0
english                 0
assignments             0
absences                0
average_score           0
grade                   0
passed                  0
dtype: int64

In [ ]:
df.isnull().sum()

student_id              0
name                    0
gender                  0
age                     0
city                    0
department              0
attendance              0
study_hours_per_week    0
math                    0
science                 0
english                 0
assignments             0
absences                0
average_score           0
grade                   0
passed                  0
dtype: int64

## 32. Create missing values for practice

In [42]:
df_missing = df.copy()

In [44]:
import numpy as  np

In [45]:
df_missing.loc[2, 'math'] = np.nan

In [46]:
df_missing.loc[5, 'city'] = np.nan

In [47]:
df_missing.isna().sum()

student_id       0
name             0
gender           0
age              0
city             1
department       0
attendance       0
study_hours      0
math             1
science          0
english          0
assignments      0
absences         0
average_score    0
grade            0
passed           0
dtype: int64

## 33. Fill missing numeric values

In [48]:
df_missing['math'] = df_missing['math'].fillna(df_missing['math'].mean())

In [49]:
df_missing['math'].isna().sum()

np.int64(0)

## 34. Fill missing categorical values

In [50]:
df_missing['city'] = df_missing['city'].fillna('Unknown')

In [51]:
df_missing['city'].isna().sum()

np.int64(0)

## 35. Drop rows containing missing values

In [ ]:
df_missing.dropna()

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88.000000,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72.000000,70,76,74,8,73.00,C,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,80.315789,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94.000000,90,92,95,1,92.75,A,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75.000000,78,81,79,6,78.25,C,True
5,1006,Fiona,F,21,Unknown,IT,91,13,86.000000,88,84,85,2,85.75,B,True
6,1007,George,M,23,Pokhara,Science,73,6,65.000000,62,69,67,12,65.75,D,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89.000000,91,87,92,4,89.75,A,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70.000000,74,79,72,7,73.75,C,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96.000000,94,95,97,1,95.50,A,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84.000000,82,86,83,5,83.75,B,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68.000000,71,73,70,9,70.50,C,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61.000000,59,65,60,14,61.25,D,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92.000000,89,94,91,2,91.50,A,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77.000000,80,82,78,6,79.25,B,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90.000000,92,89,93,3,91.00,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87.000000,85,91,88,4,87.75,B,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64.000000,66,70,65,11,66.25,D,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73.000000,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95.000000,91,93,94,2,93.25,A,True

## 36. Drop rows only when a particular column is missing

In [ ]:
df_missing.dropna(subset=['math'])

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88.000000,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,Pokhara,Management,78,8,72.000000,70,76,74,8,73.00,C,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,80.315789,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94.000000,90,92,95,1,92.75,A,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75.000000,78,81,79,6,78.25,C,True
5,1006,Fiona,F,21,Unknown,IT,91,13,86.000000,88,84,85,2,85.75,B,True
6,1007,George,M,23,Pokhara,Science,73,6,65.000000,62,69,67,12,65.75,D,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89.000000,91,87,92,4,89.75,A,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70.000000,74,79,72,7,73.75,C,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96.000000,94,95,97,1,95.50,A,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84.000000,82,86,83,5,83.75,B,True
11,1012,Lily,F,20,Pokhara,Management,76,7,68.000000,71,73,70,9,70.50,C,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61.000000,59,65,60,14,61.25,D,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92.000000,89,94,91,2,91.50,A,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77.000000,80,82,78,6,79.25,B,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90.000000,92,89,93,3,91.00,A,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87.000000,85,91,88,4,87.75,B,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64.000000,66,70,65,11,66.25,D,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73.000000,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95.000000,91,93,94,2,93.25,A,True

## 37. Replace values

In [ ]:
df['city'].replace('Kathmandu', 'KTM')

0           KTM
1       Pokhara
2           KTM
3      Lalitpur
4     Bhaktapur
5           KTM
6       Pokhara
7      Lalitpur
8           KTM
9     Bhaktapur
10          KTM
11      Pokhara
12     Lalitpur
13          KTM
14      Pokhara
15    Bhaktapur
16          KTM
17     Lalitpur
18      Pokhara
19          KTM
Name: city, dtype: str

In [ ]:
df.replace({'Kathmandu': 'KTM', 'Pokhara': 'PKR'})

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,KTM,IT,92,12,88,85,90,87,2,87.50,B,True
1,1002,Bob,M,21,PKR,Management,78,8,72,70,76,74,8,73.00,C,True
2,1003,Charlie,M,19,KTM,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True
5,1006,Fiona,F,21,KTM,IT,91,13,86,88,84,85,2,85.75,B,True
6,1007,George,M,23,PKR,Science,73,6,65,62,69,67,12,65.75,D,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
8,1009,Ian,M,22,KTM,Management,80,8,70,74,79,72,7,73.75,C,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
10,1011,Kevin,M,21,KTM,IT,87,10,84,82,86,83,5,83.75,B,True
11,1012,Lily,F,20,PKR,Management,76,7,68,71,73,70,9,70.50,C,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True
13,1014,Nina,F,22,KTM,IT,93,14,92,89,94,91,2,91.50,A,True
14,1015,Oscar,M,21,PKR,Management,82,9,77,80,82,78,6,79.25,B,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
16,1017,Quinn,M,23,KTM,IT,85,11,87,85,91,88,4,87.75,B,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
18,1019,Sam,M,22,PKR,Management,79,8,73,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,KTM,IT,94,13,95,91,93,94,2,93.25,A,True

## 38. String operations — names

In [ ]:
df['name'].str.upper()

0       ALICE
1         BOB
2     CHARLIE
3       DIANA
4        EVAN
5       FIONA
6      GEORGE
7      HANNAH
8         IAN
9       JULIA
10      KEVIN
11       LILY
12    MICHAEL
13       NINA
14      OSCAR
15      PRIYA
16      QUINN
17     RACHEL
18        SAM
19       TINA
Name: name, dtype: str

In [ ]:
df['name'].str.lower()

0       alice
1         bob
2     charlie
3       diana
4        evan
5       fiona
6      george
7      hannah
8         ian
9       julia
10      kevin
11       lily
12    michael
13       nina
14      oscar
15      priya
16      quinn
17     rachel
18        sam
19       tina
Name: name, dtype: str

In [ ]:
df['name'].str.title()

0       Alice
1         Bob
2     Charlie
3       Diana
4        Evan
5       Fiona
6      George
7      Hannah
8         Ian
9       Julia
10      Kevin
11       Lily
12    Michael
13       Nina
14      Oscar
15      Priya
16      Quinn
17     Rachel
18        Sam
19       Tina
Name: name, dtype: str

In [ ]:
df['name'].str.len()

0     5
1     3
2     7
3     5
4     4
5     5
6     6
7     6
8     3
9     5
10    5
11    4
12    7
13    4
14    5
15    5
16    5
17    6
18    3
19    4
Name: name, dtype: int64

## 39. String filtering

In [ ]:
df[df['name'].str.startswith('A')]

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.5,B,True

In [53]:
df[df['name'].str.contains('a', case=False)]

,student_id,name,gender,age,city,department,attendance,study_hours,math,science,english,assignments,absences,average_score,grade,passed
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True

## 40. GroupBy — average score by department

In [ ]:
df.groupby('department')['average_score'].mean()

department
IT            88.718750
Management    75.041667
Science       78.750000
Name: average_score, dtype: float64

## 41. GroupBy — average subject marks

In [ ]:
df.groupby('department')[['math', 'science', 'english']].mean()

                 math    science    english
department
IT          89.000000  88.000000  89.125000
Management  72.500000  74.833333  78.166667
Science     78.333333  77.166667  80.000000

## 42. GroupBy — maximum marks

In [ ]:
df.groupby('department')['average_score'].max()

department
IT            93.25
Management    79.25
Science       95.50
Name: average_score, dtype: float64

## 43. GroupBy — minimum marks

In [ ]:
df.groupby('department')['average_score'].min()

department
IT            83.75
Management    70.50
Science       61.25
Name: average_score, dtype: float64

## 44. GroupBy — count students

In [ ]:
df.groupby('department')['student_id'].count()

department
IT            8
Management    6
Science       6
Name: student_id, dtype: int64

## 45. GroupBy with multiple aggregations

In [ ]:
df.groupby('department')['average_score'].agg(['count', 'mean', 'min', 'max'])

            count       mean    min    max
department
IT              8  88.718750  83.75  93.25
Management      6  75.041667  70.50  79.25
Science         6  78.750000  61.25  95.50

## 46. GroupBy by city

In [ ]:
df.groupby('city')['average_score'].mean()

city
Bhaktapur    88.25000
Kathmandu    86.71875
Lalitpur     77.50000
Pokhara      72.80000
Name: average_score, dtype: float64

## 47. GroupBy by two columns

In [ ]:
df.groupby(['city', 'department'])['average_score'].mean()

city       department
Bhaktapur  Management    78.250000
           Science       93.250000
Kathmandu  IT            88.571429
           Management    73.750000
Lalitpur   IT            89.750000
           Science       73.416667
Pokhara    Management    74.562500
           Science       65.750000
Name: average_score, dtype: float64

## 48. `agg()` with different functions

In [ ]:
df.groupby('department').agg(
    average_score=('average_score', 'mean'),
    highest_score=('average_score', 'max'),
    lowest_score=('average_score', 'min'),
    students=('student_id', 'count')
)

            average_score  highest_score  lowest_score  students
department
IT              88.718750          93.25         83.75         8
Management      75.041667          79.25         70.50         6
Science         78.750000          95.50         61.25         6

## 49. `transform()` — add department average to every student

In [ ]:
df['department_average'] = df.groupby('department')['average_score'].transform('mean')

In [ ]:
df[['name', 'department', 'average_score', 'department_average']]

       name  department  average_score  department_average
0     Alice          IT          87.50           88.718750
1       Bob  Management          73.00           75.041667
2   Charlie          IT          90.50           88.718750
3     Diana     Science          92.75           78.750000
4      Evan  Management          78.25           75.041667
5     Fiona          IT          85.75           88.718750
6    George     Science          65.75           78.750000
7    Hannah          IT          89.75           88.718750
8       Ian  Management          73.75           75.041667
9     Julia     Science          95.50           78.750000
10    Kevin          IT          83.75           88.718750
11     Lily  Management          70.50           75.041667
12  Michael     Science          61.25           78.750000
13     Nina          IT          91.50           88.718750
14    Oscar  Management          79.25           75.041667
15    Priya     Science          91.00           78.750000
16    Quinn          IT          87.75           88.718750
17   Rachel     Science          66.25           78.750000
18      Sam  Management          75.50           75.041667
19     Tina          IT          93.25           88.718750

## 50. Compare a student to the department average

In [ ]:
df['above_department_average'] = df['average_score'] > df['department_average']

In [ ]:
df[['name', 'department', 'average_score', 'department_average', 'above_department_average']]

,name,department,average_score,department_average,above_department_average
0,Alice,IT,87.50,88.718750,False
1,Bob,Management,73.00,75.041667,False
2,Charlie,IT,90.50,88.718750,True
3,Diana,Science,92.75,78.750000,True
4,Evan,Management,78.25,75.041667,True
5,Fiona,IT,85.75,88.718750,False
6,George,Science,65.75,78.750000,False
7,Hannah,IT,89.75,88.718750,True
8,Ian,Management,73.75,75.041667,False
9,Julia,Science,95.50,78.750000,True
10,Kevin,IT,83.75,88.718750,False
11,Lily,Management,70.50,75.041667,False
12,Michael,Science,61.25,78.750000,False
13,Nina,IT,91.50,88.718750,True
14,Oscar,Management,79.25,75.041667,True
15,Priya,Science,91.00,78.750000,True
16,Quinn,IT,87.75,88.718750,False
17,Rachel,Science,66.25,78.750000,False
18,Sam,Management,75.50,75.041667,True
19,Tina,IT,93.25,88.718750,True

## 51. Correlation

In [ ]:
df[['age', 'attendance', 'study_hours_per_week', 'math', 'science', 'english', 'average_score']].corr()

,age,attendance,study_hours_per_week,math,science,english,average_score
age,1.000000,-0.331966,-0.252617,-0.311058,-0.422041,-0.282033,-0.344800
attendance,-0.331966,1.000000,0.976414,0.970870,0.949639,0.961614,0.972397
study_hours_per_week,-0.252617,0.976414,1.000000,0.950459,0.912709,0.943394,0.947232
math,-0.311058,0.970870,0.950459,1.000000,0.969755,0.971967,0.994292
science,-0.422041,0.949639,0.912709,0.969755,1.000000,0.949294,0.984903
english,-0.282033,0.961614,0.943394,0.971967,0.949294,1.000000,0.981803
average_score,-0.344800,0.972397,0.947232,0.994292,0.984903,0.981803,1.000000

## 52. Covariance

In [ ]:
df[['study_hours_per_week', 'average_score']].cov()

                      study_hours_per_week  average_score
study_hours_per_week              8.681579      29.296053
average_score                    29.296053     110.180921

## 53. Create a pivot table

In [ ]:
df.pivot_table(index='department', values='average_score', aggfunc='mean')

            average_score
department
IT              88.718750
Management      75.041667
Science         78.750000

## 54. Pivot table with multiple values

In [ ]:
df.pivot_table(index='department', values=['math', 'science', 'english'], aggfunc='mean')

              english       math    science
department
IT          89.125000  89.000000  88.000000
Management  78.166667  72.500000  74.833333
Science     80.000000  78.333333  77.166667

## 55. Pivot table by city and department

In [ ]:
df.pivot_table(index='city', columns='department', values='average_score', aggfunc='mean')

department         IT  Management    Science
city
Bhaktapur         NaN     78.2500  93.250000
Kathmandu   88.571429     73.7500        NaN
Lalitpur    89.750000         NaN  73.416667
Pokhara           NaN     74.5625  65.750000

## 56. Duplicate rows

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates()

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed,department_average,above_department_average
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True,88.718750,False
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True,75.041667,False
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True,88.718750,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True,78.750000,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True,75.041667,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True,88.718750,False
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True,78.750000,False
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True,88.718750,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True,75.041667,False
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True,78.750000,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True,88.718750,False
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True,75.041667,False
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True,78.750000,False
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True,88.718750,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True,75.041667,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True,78.750000,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True,88.718750,False
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True,78.750000,False
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True,75.041667,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True,88.718750,True

## 57. Data types

In [ ]:
df.dtypes

student_id                    int64
name                            str
gender                          str
age                           int64
city                            str
department                      str
attendance                    int64
study_hours_per_week          int64
math                          int64
science                       int64
english                       int64
assignments                   int64
absences                      int64
average_score               float64
grade                           str
passed                         bool
department_average          float64
above_department_average       bool
dtype: object

## 58. Convert a column's type

In [ ]:
df['age'] = df['age'].astype(int)

In [ ]:
df['department'] = df['department'].astype('category')

In [ ]:
df.dtypes

student_id                     int64
name                             str
gender                           str
age                            int64
city                             str
department                  category
attendance                     int64
study_hours_per_week           int64
math                           int64
science                        int64
english                        int64
assignments                    int64
absences                       int64
average_score                float64
grade                            str
passed                          bool
department_average           float64
above_department_average        bool
dtype: object

## 59. Reset the index

In [ ]:
df.reset_index(drop=True)

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed,department_average,above_department_average
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True,88.718750,False
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True,75.041667,False
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True,88.718750,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True,78.750000,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True,75.041667,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True,88.718750,False
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True,78.750000,False
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True,88.718750,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True,75.041667,False
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True,78.750000,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True,88.718750,False
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True,75.041667,False
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True,78.750000,False
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True,88.718750,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True,75.041667,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True,78.750000,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True,88.718750,False
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True,78.750000,False
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True,75.041667,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True,88.718750,True

## 60. Set a student ID as index

In [ ]:
df_indexed = df.set_index('student_id')

In [ ]:
df_indexed.head()

,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed,department_average,above_department_average
student_id,,,,,,,,,,,,,,,,,
1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True,88.718750,False
1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True,75.041667,False
1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True,88.718750,True
1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True,78.750000,True
1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True,75.041667,True

## 61. Convert back to normal index

In [ ]:
df_indexed.reset_index()

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed,department_average,above_department_average
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True,88.718750,False
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True,75.041667,False
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True,88.718750,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True,78.750000,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True,75.041667,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True,88.718750,False
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True,78.750000,False
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True,88.718750,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True,75.041667,False
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True,78.750000,True
10,1011,Kevin,M,21,Kathmandu,IT,87,10,84,82,86,83,5,83.75,B,True,88.718750,False
11,1012,Lily,F,20,Pokhara,Management,76,7,68,71,73,70,9,70.50,C,True,75.041667,False
12,1013,Michael,M,24,Lalitpur,Science,69,5,61,59,65,60,14,61.25,D,True,78.750000,False
13,1014,Nina,F,22,Kathmandu,IT,93,14,92,89,94,91,2,91.50,A,True,88.718750,True
14,1015,Oscar,M,21,Pokhara,Management,82,9,77,80,82,78,6,79.25,B,True,75.041667,True
15,1016,Priya,F,20,Bhaktapur,Science,90,12,90,92,89,93,3,91.00,A,True,78.750000,True
16,1017,Quinn,M,23,Kathmandu,IT,85,11,87,85,91,88,4,87.75,B,True,88.718750,False
17,1018,Rachel,F,19,Lalitpur,Science,72,6,64,66,70,65,11,66.25,D,True,78.750000,False
18,1019,Sam,M,22,Pokhara,Management,79,8,73,76,78,75,8,75.50,C,True,75.041667,True
19,1020,Tina,F,21,Kathmandu,IT,94,13,95,91,93,94,2,93.25,A,True,88.718750,True

## 62. Merge two student-related DataFrames

In [ ]:
attendance_extra = df[['student_id', 'attendance']].copy()
attendance_extra['attendance_status'] = np.where(
    attendance_extra['attendance'] >= 80, 'Good', 'Low'
)
attendance_extra.head()

   student_id  attendance attendance_status
0        1001          92              Good
1        1002          78               Low
2        1003          88              Good
3        1004          95              Good
4        1005          84              Good

In [ ]:
student_basic = df[['student_id', 'name', 'department']].copy()

In [ ]:
pd.merge(student_basic, attendance_extra, on='student_id')

    student_id     name  department  attendance attendance_status
0         1001    Alice          IT          92              Good
1         1002      Bob  Management          78               Low
2         1003  Charlie          IT          88              Good
3         1004    Diana     Science          95              Good
4         1005     Evan  Management          84              Good
5         1006    Fiona          IT          91              Good
6         1007   George     Science          73               Low
7         1008   Hannah          IT          89              Good
8         1009      Ian  Management          80              Good
9         1010    Julia     Science          96              Good
10        1011    Kevin          IT          87              Good
11        1012     Lily  Management          76               Low
12        1013  Michael     Science          69               Low
13        1014     Nina          IT          93              Good
14        1015    Oscar  Management          82              Good
15        1016    Priya     Science          90              Good
16        1017    Quinn          IT          85              Good
17        1018   Rachel     Science          72               Low
18        1019      Sam  Management          79               Low
19        1020     Tina          IT          94              Good

## 63. Merge with `how='left'`

In [ ]:
pd.merge(student_basic, attendance_extra, on='student_id', how='left')

    student_id     name  department  attendance attendance_status
0         1001    Alice          IT          92              Good
1         1002      Bob  Management          78               Low
2         1003  Charlie          IT          88              Good
3         1004    Diana     Science          95              Good
4         1005     Evan  Management          84              Good
5         1006    Fiona          IT          91              Good
6         1007   George     Science          73               Low
7         1008   Hannah          IT          89              Good
8         1009      Ian  Management          80              Good
9         1010    Julia     Science          96              Good
10        1011    Kevin          IT          87              Good
11        1012     Lily  Management          76               Low
12        1013  Michael     Science          69               Low
13        1014     Nina          IT          93              Good
14        1015    Oscar  Management          82              Good
15        1016    Priya     Science          90              Good
16        1017    Quinn          IT          85              Good
17        1018   Rachel     Science          72               Low
18        1019      Sam  Management          79               Low
19        1020     Tina          IT          94              Good

## 64. Concatenate DataFrames

In [ ]:
part1 = df.iloc[:5]

In [ ]:
part2 = df.iloc[5:10]

In [ ]:
pd.concat([part1, part2], ignore_index=True)

,student_id,name,gender,age,city,department,attendance,study_hours_per_week,math,science,english,assignments,absences,average_score,grade,passed,department_average,above_department_average
0,1001,Alice,F,20,Kathmandu,IT,92,12,88,85,90,87,2,87.50,B,True,88.718750,False
1,1002,Bob,M,21,Pokhara,Management,78,8,72,70,76,74,8,73.00,C,True,75.041667,False
2,1003,Charlie,M,19,Kathmandu,IT,88,10,91,93,88,90,3,90.50,A,True,88.718750,True
3,1004,Diana,F,22,Lalitpur,Science,95,14,94,90,92,95,1,92.75,A,True,78.750000,True
4,1005,Evan,M,20,Bhaktapur,Management,84,9,75,78,81,79,6,78.25,C,True,75.041667,True
5,1006,Fiona,F,21,Kathmandu,IT,91,13,86,88,84,85,2,85.75,B,True,88.718750,False
6,1007,George,M,23,Pokhara,Science,73,6,65,62,69,67,12,65.75,D,True,78.750000,False
7,1008,Hannah,F,20,Lalitpur,IT,89,11,89,91,87,92,4,89.75,A,True,88.718750,True
8,1009,Ian,M,22,Kathmandu,Management,80,8,70,74,79,72,7,73.75,C,True,75.041667,False
9,1010,Julia,F,19,Bhaktapur,Science,96,15,96,94,95,97,1,95.50,A,True,78.750000,True

## 65. Date handling — use a separate student enrollment example

In [ ]:
dates = pd.DataFrame({
    'student_id': [1001, 1002, 1003, 1004],
    'enrollment_date': ['2025-01-15', '2025-02-20', '2025-03-10', '2025-04-05']
})

In [ ]:
dates['enrollment_date'] = pd.to_datetime(dates['enrollment_date'])

In [ ]:
dates['enrollment_date'].dt.year

0    2025
1    2025
2    2025
3    2025
Name: enrollment_date, dtype: int32

In [ ]:
dates['enrollment_date'].dt.month

0    1
1    2
2    3
3    4
Name: enrollment_date, dtype: int32

In [ ]:
dates['enrollment_date'].dt.day

0    15
1    20
2    10
3     5
Name: enrollment_date, dtype: int32

In [ ]:
dates['enrollment_date'].dt.day_name()

0    Wednesday
1     Thursday
2       Monday
3     Saturday
Name: enrollment_date, dtype: str

## 66. `apply()`

In [ ]:
df['score_plus_5'] = df['average_score'].apply(lambda x: x + 5)

In [ ]:
df[['name', 'average_score', 'score_plus_5']]

       name  average_score  score_plus_5
0     Alice          87.50         92.50
1       Bob          73.00         78.00
2   Charlie          90.50         95.50
3     Diana          92.75         97.75
4      Evan          78.25         83.25
5     Fiona          85.75         90.75
6    George          65.75         70.75
7    Hannah          89.75         94.75
8       Ian          73.75         78.75
9     Julia          95.50        100.50
10    Kevin          83.75         88.75
11     Lily          70.50         75.50
12  Michael          61.25         66.25
13     Nina          91.50         96.50
14    Oscar          79.25         84.25
15    Priya          91.00         96.00
16    Quinn          87.75         92.75
17   Rachel          66.25         71.25
18      Sam          75.50         80.50
19     Tina          93.25         98.25

## 67. Row-wise `apply()`

In [ ]:
df['study_attendance_score'] = df.apply(lambda row: row['study_hours_per_week'] + row['attendance'], axis=1)

In [ ]:
df[['name', 'study_attendance_score']]

       name  study_attendance_score
0     Alice                     104
1       Bob                      86
2   Charlie                      98
3     Diana                     109
4      Evan                      93
5     Fiona                     104
6    George                      79
7    Hannah                     100
8       Ian                      88
9     Julia                     111
10    Kevin                      97
11     Lily                      83
12  Michael                      74
13     Nina                     107
14    Oscar                      91
15    Priya                     102
16    Quinn                      96
17   Rachel                      78
18      Sam                      87
19     Tina                     107

## 68. `map()`

In [ ]:
df['gender_full'] = df['gender'].map({'F': 'Female', 'M': 'Male'})

In [ ]:
df[['name', 'gender', 'gender_full']]

       name gender gender_full
0     Alice      F      Female
1       Bob      M        Male
2   Charlie      M        Male
3     Diana      F      Female
4      Evan      M        Male
5     Fiona      F      Female
6    George      M        Male
7    Hannah      F      Female
8       Ian      M        Male
9     Julia      F      Female
10    Kevin      M        Male
11     Lily      F      Female
12  Michael      M        Male
13     Nina      F      Female
14    Oscar      M        Male
15    Priya      F      Female
16    Quinn      M        Male
17   Rachel      F      Female
18      Sam      M        Male
19     Tina      F      Female

## 69. Rolling average

In [ ]:
df['rolling_average'] = df['average_score'].rolling(window=3).mean()

In [ ]:
df[['name', 'average_score', 'rolling_average']]

       name  average_score  rolling_average
0     Alice          87.50              NaN
1       Bob          73.00              NaN
2   Charlie          90.50        83.666667
3     Diana          92.75        85.416667
4      Evan          78.25        87.166667
5     Fiona          85.75        85.583333
6    George          65.75        76.583333
7    Hannah          89.75        80.416667
8       Ian          73.75        76.416667
9     Julia          95.50        86.333333
10    Kevin          83.75        84.333333
11     Lily          70.50        83.250000
12  Michael          61.25        71.833333
13     Nina          91.50        74.416667
14    Oscar          79.25        77.333333
15    Priya          91.00        87.250000
16    Quinn          87.75        86.000000
17   Rachel          66.25        81.666667
18      Sam          75.50        76.500000
19     Tina          93.25        78.333333

## 70. Cumulative score

In [ ]:
df['cumulative_average_score'] = df['average_score'].cumsum()

In [ ]:
df[['name', 'average_score', 'cumulative_average_score']]

       name  average_score  cumulative_average_score
0     Alice          87.50                     87.50
1       Bob          73.00                    160.50
2   Charlie          90.50                    251.00
3     Diana          92.75                    343.75
4      Evan          78.25                    422.00
5     Fiona          85.75                    507.75
6    George          65.75                    573.50
7    Hannah          89.75                    663.25
8       Ian          73.75                    737.00
9     Julia          95.50                    832.50
10    Kevin          83.75                    916.25
11     Lily          70.50                    986.75
12  Michael          61.25                   1048.00
13     Nina          91.50                   1139.50
14    Oscar          79.25                   1218.75
15    Priya          91.00                   1309.75
16    Quinn          87.75                   1397.50
17   Rachel          66.25                   1463.75
18      Sam          75.50                   1539.25
19     Tina          93.25                   1632.50

## 71. Export the cleaned DataFrame to CSV

In [ ]:
df.to_csv('students_cleaned.csv', index=False)

# 🟡 Intermediate Mini Project
## Student Performance Analysis

Answer these using Pandas:

1. How many students are in the dataset?
2. What departments are present?
3. What is the average math score?
4. Which student has the highest average score?
5. Which 5 students have the lowest average score?
6. What is the average score by department?
7. What is the average attendance by department?
8. Which city has the highest average score?
9. How many students are in each department?
10. How many students passed?
11. What percentage of students passed?
12. What is the relationship between study hours and average score?
13. Find students with attendance below 80.
14. Find students with average score above the department average.
15. Find the average math, science, and English score by department.
16. Sort students from highest to lowest average score.
17. Create a pivot table of average score by city and department.
18. Find students who have more than 10 absences.
19. Find the average score of students with attendance >= 90.
20. Save the final analysis to CSV.

In [ ]:
# Write your answers here.
# Q1:
# Q2:
# Q3:
# ...

# 🔵 Interview / Viva Questions

### Beginner
1. What is Pandas?
2. What is a DataFrame?
3. What does `pd.read_csv()` do?
4. What does `df.head()` do?
5. What does `df.shape` return?
6. What does `df.columns` return?
7. What is `df.info()` used for?
8. What is the difference between one-column and multiple-column selection?
9. What is `loc`?
10. What is `iloc`?
11. How do you filter rows?
12. How do you check missing values?
13. How do you remove missing rows?
14. How do you fill missing values?
15. How do you sort a DataFrame?

### Intermediate
16. What does `groupby()` do?
17. What is `agg()`?
18. What is `transform()`?
19. Difference between `apply()`, `map()`, and `transform()`?
20. What does `value_counts()` do?
21. What does `nunique()` do?
22. How do you find the top 5 students?
23. What is a pivot table?
24. Difference between `merge()` and `concat()`?
25. How do you convert a column to datetime?
26. How do you extract year/month/day?
27. How do you detect duplicates?
28. Why use `astype()`?
29. What does `corr()` calculate?
30. How do you export a DataFrame to CSV?

# 🔵 Challenge: write code without looking back

### Challenge 1
Find the students whose:
- attendance is at least 85
- math is at least 80
- average score is at least 80

### Challenge 2
Find the average score for every city and sort from highest to lowest.

### Challenge 3
Find the department with the highest average attendance.

### Challenge 4
Find the top 3 students in every department.

### Challenge 5
Create a column:
- `Excellent` if average >= 90
- `Good` if average >= 80
- `Average` if average >= 70
- `Needs Improvement` otherwise

### Challenge 6
Calculate each student's difference from the average score of their department.

### Challenge 7
Find whether study hours and average score have a positive or negative correlation.

### Challenge 8
Create a report containing:
`department`, number of students, average attendance, average score, highest score.

### Challenge 9
Save that report as `department_report.csv`.

### Challenge 10
Explain each line of your final solution to another student.

# Final teaching flow

For a beginner class, teach in this order:

**Day/Part 1**
1. `read_csv`
2. `head`, `tail`, `shape`, `columns`, `dtypes`, `info`
3. column selection
4. `loc`, `iloc`
5. filtering

**Day/Part 2**
6. adding columns
7. renaming/dropping
8. sorting
9. `unique`, `nunique`, `value_counts`
10. statistics
11. missing values

**Day/Part 3**
12. `groupby`
13. `agg`
14. `transform`
15. pivot tables
16. merge/concat

**Day/Part 4**
17. strings
18. datetime
19. apply/map
20. correlation
21. practical project
22. interview questions