In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("Libraries imported successfully!")

Libraries imported successfully!

In [8]:
##Dataset Load

df = pd.read_csv("all_stocks_5yr.csv")

df.head()

         date   open   high    low  close    volume Name
0  2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL
1  2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL
2  2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL
3  2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4  2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL

In [ ]:
##Dataset info

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 619040 entries, 0 to 619039
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    619040 non-null  str
 1   open    619029 non-null  float64
 2   high    619032 non-null  float64
 3   low     619032 non-null  float64
 4   close   619040 non-null  float64
 5   volume  619040 non-null  int64
 6   Name    619040 non-null  str
dtypes: float64(4), int64(1), str(2)
memory usage: 33.1 MB

In [9]:
##Missing Values Check

df.isnull().sum()

date       0
open      11
high       8
low        8
close      0
volume     0
Name       0
dtype: int64

In [ ]:
##Dataset Clean

df = df.dropna()

print("Dataset cleaned successfully!")
print("Total rows:", len(df))

Dataset cleaned successfully!
Total rows: 619029

In [10]:
##Company Select

stock = df[df["Name"] == "AAPL"].copy()

stock.head()

            date     open     high      low    close     volume  Name
1259  2013-02-08  67.7142  68.4014  66.8928  67.8542  158168416  AAPL
1260  2013-02-11  68.0714  69.2771  67.6071  68.5614  129029425  AAPL
1261  2013-02-12  68.5014  68.9114  66.8205  66.8428  151829363  AAPL
1262  2013-02-13  66.7442  67.6628  66.1742  66.7156  118721995  AAPL
1263  2013-02-14  66.3599  67.3771  66.2885  66.6556   88809154  AAPL

In [7]:
X = stock[["open", "high", "low", "volume"]]
y = stock["close"]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
         open     high      low     volume
1259  67.7142  68.4014  66.8928  158168416
1260  68.0714  69.2771  67.6071  129029425
1261  68.5014  68.9114  66.8205  151829363
1262  66.7442  67.6628  66.1742  118721995
1263  66.3599  67.3771  66.2885   88809154

Target:
1259    67.8542
1260    68.5614
1261    66.8428
1262    66.7156
1263    66.6556
Name: close, dtype: float64

In [ ]:
## 4. Splitting the Dataset into Training and Testing Sets

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (1007, 4)
Testing data: (252, 4)

In [13]:
## Multiple Linear Regression

linear_model = LinearRegression()

linear_model.fit(X_train, y_train)

linear_predictions = linear_model.predict(X_test)

print("Multiple Linear Regression trained successfully!")

Multiple Linear Regression trained successfully!

In [14]:
## Decision Tree Regression:

tree_model = DecisionTreeRegressor(random_state=42)

tree_model.fit(X_train, y_train)

tree_predictions = tree_model.predict(X_test)

print("Decision Tree Regression trained successfully!")

Decision Tree Regression trained successfully!

In [15]:
# Evaluate Multiple Linear Regression

linear_mae = mean_absolute_error(y_test, linear_predictions)
linear_mse = mean_squared_error(y_test, linear_predictions)
linear_rmse = np.sqrt(linear_mse)
linear_r2 = r2_score(y_test, linear_predictions)

print("Multiple Linear Regression")
print("MAE :", linear_mae)
print("MSE :", linear_mse)
print("RMSE:", linear_rmse)
print("R²  :", linear_r2)

Multiple Linear Regression
MAE : 0.6107330912480372
MSE : 0.7026219410015578
RMSE: 0.8382254714583409
R²  : 0.9992350302126645

In [16]:
# Evaluate Decision Tree Regression

tree_mae = mean_absolute_error(y_test, tree_predictions)
tree_mse = mean_squared_error(y_test, tree_predictions)
tree_rmse = np.sqrt(tree_mse)
tree_r2 = r2_score(y_test, tree_predictions)

print("Decision Tree Regression")
print("MAE :", tree_mae)
print("MSE :", tree_mse)
print("RMSE:", tree_rmse)
print("R²  :", tree_r2)

Decision Tree Regression
MAE : 0.7014119047619058
MSE : 0.9693902220634923
RMSE: 0.9845761636681504
R²  : 0.9989445899868142

In [17]:
## Model Comparison

comparison = pd.DataFrame({
    "Model": [
        "Multiple Linear Regression",
        "Decision Tree Regression"
    ],
    "MAE": [
        linear_mae,
        tree_mae
    ],
    "MSE": [
        linear_mse,
        tree_mse
    ],
    "RMSE": [
        linear_rmse,
        tree_rmse
    ],
    "R² Score": [
        linear_r2,
        tree_r2
    ]
})

comparison

                        Model       MAE       MSE      RMSE  R² Score
0  Multiple Linear Regression  0.610733  0.702622  0.838225  0.999235
1    Decision Tree Regression  0.701412  0.969390  0.984576  0.998945